name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Install Frontend Dependencies
      run: npm ci

    - name: Build Frontend
      run: npm run build

    - name: Test Frontend
      run: npm run test

    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm ci

    - name: Generate Prisma Client
      working-directory: ./backend
      run: npx prisma generate

    - name: Build Backend
      working-directory: ./backend
      run: npm run build

    - name: Test Backend
      working-directory: ./backend
      run: npm run test
